# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_legal_name', models.CharField(max_length=150)),
                ('zip_code', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=250)),
                ('house', models.CharField(max_length=50)),
                ('registration_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('ceo', models.CharField(max_length=100)),
                ('inn', models.IntegerField()),
                ('OGRN', models.IntegerField()),
                ('OKPO', models.IntegerField()),
                ('KPP', models.IntegerField()),
            ],
        ),
    ]
