# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 16:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField()),
                ('requested_amount', models.IntegerField()),
                ('approved_date', models.DateField()),
                ('approved_amount', models.IntegerField()),
                ('expiration_date', models.DateField(null=True)),
                ('guarantor_comment', models.TextField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='modified',
            field=models.DateField(default=datetime.datetime(2018, 1, 19, 16, 17, 29, 807450, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='insurer',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
    ]
