# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20180119_1917'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditlimit',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Contract'),
        ),
        migrations.AddField(
            model_name='creditlimit',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Currency'),
        ),
        migrations.AddField(
            model_name='creditlimit',
            name='debitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='creditlimit',
            name='guarantor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='granted_limits', to='companies.Company'),
        ),
        migrations.AddField(
            model_name='creditlimit',
            name='insurer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Insurer'),
        ),
    ]
