# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20180119_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditlimit',
            name='insurer',
        ),
    ]
