# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_remove_creditlimit_insurer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditlimit',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='creditlimit',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='creditlimit',
            name='debitor',
        ),
        migrations.RemoveField(
            model_name='creditlimit',
            name='guarantor',
        ),
        migrations.RemoveField(
            model_name='insurer',
            name='company',
        ),
        migrations.DeleteModel(
            name='CreditLimit',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
